export const actionTypes = {
  SET_BLUR: 'SET_BLUR',
  SET_FILTER_PARAMS: 'SET_FILTER_PARAMS',
  SET_MOVIE_ID: 'SET_MOVIE_ID',
  SET_LOADING_STATE: 'SET_LOADING_STATE',
  SET_SEANCE_ID: 'SET_SEANCE_ID',
  SET_BOOKING_STAGE: 'SET_BOOKING_STAGE',

  FILTERS_REQUESTED: 'FILTERS_REQUESTED',
  FILTERS_LOADED: 'FILTERS_LOADED',
  FILTERS_FAILED: 'FILTERS_FAILED',

  MOVIE_REQUESTED: 'MOVIE_REQUESTED',
  MOVIE_LOADED: 'MOVIE_LOADED',
  MOVIE_FAILED: 'MOVIE_FAILED',

  MOVIES_REQUESTED: 'MOVIES_REQUESTED',
  MOVIES_LOADED: 'MOVIES_LOADED',
  MOVIES_FAILED: 'MOVIES_FAILED',

  SEANCES_REQUESTED: 'SEANCES_REQUESTED',
  SEANCES_LOADED: 'SEANCES_LOADED',
  SEANCES_FAILED: 'SEANCES_FAILED',

  SEANCE_REQUESTED: 'SEANCE_REQUESTED',
  SEANCE_LOADED: 'SEANCE_LOADED',
  SEANCE_FAILED: 'SEANCE_FAILED',

  USER_NAME_REQUESTED: 'USER_NAME_REQUESTED',
  USER_NAME_LOADED: 'USER_NAME_LOADED',
  USER_NAME_FAILED: 'USER_NAME_FAILED',
};
