export const actionTypes = {
  SET_BLUR: 'SET_BLUR',
  SET_FILTER_PARAMS: 'SET_FILTER_PARAMS',
  SET_MOVIE_ID: 'SET_MOVIE_ID',
  SET_LOADING_STATE: 'SET_LOADING_STATE',

  FILTERS_REQUESTED: 'FILTERS_REQUESTED',
  FILTERS_LOADED: 'FILTERS_LOADED',
  FILTERS_FAILED: 'FILTERS_FAILED',

  MOVIE_REQUESTED: 'MOVIE_REQUESTED',
  MOVIE_LOADED: 'MOVIE_LOADED',
  MOVIE_FAILED: 'MOVIE_FAILED',

  MOVIES_REQUESTED: 'MOVIES_REQUESTED',
  MOVIES_LOADED: 'MOVIES_LOADED',
  MOVIES_FAILED: 'MOVIES_FAILED',

  SEANCES_REQUESTED: 'SEANCES_REQUESTED',
  SEANCES_LOADED: 'SEANCES_LOADED',
  SEANCES_FAILED: 'SEANCES_FAILED'
};
